const fs = require('fs');
fs.mkdirSync('dist', { recursive: true });
const html = `<!DOCTYPE html><html><head><title>LLM Page</title></head><body><h1>Generated by LLM</h1><p>Mock content.</p></body></html>`;
fs.writeFileSync('dist/index.html', html);
console.log('dist/index.html created');
